config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}  
  resources :clinks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "clinks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clink.rb
class Clink < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :clinks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clinks_controller.rb
class ClinksController < ApplicationController
  before_action :set_clink, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @clinks = Clink.all.order("created_at DESC")
    @clink = Clink.new
  end

  def show
  end

  def new
    @clink = current_user.clinks.build
  end

  def edit
  end

  def create
    @clink = current_user.clinks.build(clink_params)

    respond_to do |format|
      if @clink.save
        format.html { redirect_to root_path, notice: 'Clink was successfully created.' }
        format.json { render :show, status: :created, location: @clink }
      else
        format.html { render :new }
        format.json { render json: @clink.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @clink.update(clink_params)
        format.html { redirect_to @clink, notice: 'Clink was successfully updated.' }
        format.json { render :show, status: :ok, location: @clink }
      else
        format.html { render :edit }
        format.json { render json: @clink.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @clink.destroy
    respond_to do |format|
      format.html { redirect_to clinks_url, notice: 'Clink was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
    def set_clink
      @clink = Clink.find(params[:id])
    end

    def clink_params
      params.require(:clink).permit(:clink)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

    def sign_up_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clinks_helper.rb
module ClinksHelper
end

app/views/clinks/_feed.html.erb
<div class="column is-half">
    <% if user_signed_in?%>
    <article class="media box">
        <figure class="media-left">
            <p class="image is-64x64">
              <%= gravatar_image_tag(current_user.email, size: 64, alt: "current_user.name")%>
            </p>
        </figure>
        <div class="media-content">
            <%= render 'clinks/form'%>
        </div>
    </article>
    <%end%>

<% @clinks.each do | clink |%>
    <div class="box">
        <article class="media">
            <div class="media-left">
                <figure class ="image is-64x64">
                   <%= gravatar_image_tag(clink.user.email, size: 64, alt: "tweet.user.name")%>
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                <strong><%= clink.user.name %></strong><br/>
                <small><%= clink.user.username %></small><br/>
                <p><%=clink.clink%></p>
            </div>
            <% if user_signed_in? && current_user.id == clink.user_id %>
            <nav class="level">
                <div class="level-left is-mobile">
                    <%= link_to clink, class: "level-item" do %>
                        <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
                    <%end%>
                    <%= link_to edit_clink_path(clink), class: "level-item" do %>
                        <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                    <%end%>
                    <%= link_to clink, method: :delete, data: { confirm: "Are you sure you want to delete this Clink?"} do %>
                        <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
                    <%end%>
                </div>
            </nav>
            <%end%>
            </div>
        </article>
    </div>
<%end%>
 </div>

app/views/clinks/_form.html.erb
<%= simple_form_for(@clink) do |f| %>
<%= f.error_notification %>
<div class="field">
  <div class="control">
  <%= f.input :clink, label: "Clink about it", input_html: { class: "textarea" }, wrapper: false, label_html: {class: "label"}, placeholder: "Compose a new clink..."%>
  </div>
</div>
<%= f.button :submit, class: "button is-info" %>
<%end%>

app/views/clinks/_profile.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Profile</p>
		<div class="panel-block">
			<article class="media">
				<div class="media-left">
					<figure class="image is-64x64">
                        <%# <%= image_tag("lukey.jpg", alt: "profile pic", height: 42, width: 42) %> 
						<%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name)  %> 
					</figure>
				</div>
				<div class="media-content">
					<div class="content">
						<p>
							<strong><%= current_user.name %></strong><br />
							<small><%= current_user.username %></small>
						</p>
					</div>
				</div>
			</article>
		</div>
		<div class="panel-block">
			<div class="level is-mobile">
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Clinks</p>
						<p class="title is-6"><%= current_user.clinks.count %></p>
					</div>
				</div>
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Following</p>
						<p class="title is-6">11</p>
					</div>
				</div>
					<div class="level-item has-centered-text">
					<div>
						<p class="heading">Followers</p>
						<p class="title is-6">4</p>
					</div>
				</div>
			</div>
		</div>
	</nav>
</div>

app/views/clinks/_trends.html.erb
<div class="column is-one-quater">
    <nav class="panel">
        <p class="panel-heading">Trends</p>
        <a class="panel-block">
            Trend 1
        </a>
        <a class="panel-block">
            Trend 2
        </a>
        <a class="panel-block">
            Trend 3
        </a>
        <a class="panel-block">
            Trend 4
        </a>
        <a class="panel-block">
            Trend 5
        </a>
        <a class="panel-block">
            Trend 6
        </a>
    </nav>
</div>

app/views/clinks/_who-to-follow.html.erb
<div class="column">
    <nav class="panel">
        <p class="panel-heading">Who To Follow</p>
    <div class="panel-block">
        <article class="media">
            <div class="media-left">
                <figure class="image is-32x32">
                    <%# <%= image_tag("tronald.jpg", alt: "Tronald") %> 
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <p>
                    <strong>Tronald Trump</strong>
                    <small>@tronald</small>
                    </p>
                </div>    
            </div>
        </article>
    </div>
    <div class="panel-block">
        <article class="media">
            <div class="media-left">
                <figure class="image is-32x32">
                    <%# <%= image_tag("bustinj.jpeg", alt: "Bustin") %> 
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <p>
                    <strong>Bustin Jieber</strong>
                    <small>@therealbj</small>
                    </p>
                </div>    
            </div>
        </article>
    </div>
    <div class="panel-block">
        <article class="media">
            <div class="media-left">
                <figure class="image is-32x32">
                    <%# <%= image_tag("saylor.jpg", alt: "Saylor") %> 
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <p>
                    <strong>Saylor Twift</strong>
                    <small>@saysay</small>
                    </p>
                </div>    
            </div>
        </article>
    </div>
        <div class="panel-block">
        <article class="media">
            <div class="media-left">
                <figure class="image is-32x32">
                    <%# <%= image_tag("lukey.jpg", alt: "Luke") %> 
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <p>
                    <strong>Luke Colcott</strong>
                    <small>@lukeylunchbox</small>
                    </p>
                </div>    
            </div>
        </article>
    </div>
</nav>

</div>

app/views/clinks/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Editing Clink</h1>
				<%= render 'form', clink: @clink %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', clinks_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/clinks/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
    <% if user_signed_in? %>
      <%= render 'profile'%>
    <% else %>
      <%= render 'trends' %>
    <%end%>
      <%= render 'feed' %>
      <%= render 'who-to-follow'%>
    </div>
  </div>
</section>

app/views/clinks/new.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Create a New Clink</h1>
					<%= render 'form', clink: @clink %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', clinks_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/clinks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Clink:</strong>
  <%= @clink.clink %>
</p>

<%= link_to 'Edit', edit_clink_path(@clink) %> |
<%= link_to 'Back', clinks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bitter</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice]%>
      <div class="notification.is-primary global-notification">
        <p class ="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert]%>
      <div class="notification.is-danger global-notification">
        <p class ="alert"><%= alert %></p>
      </div>
    <% end %>
  <nav class="navbar is-info">
    <div class = "navbar-brand">
    <%= link_to root_path, class: "navbar-item" do %>
    <h1 class = "title is-5">Bitter  <%= image_tag("bitter-logo.png", alt: "bitter logo") %></h1>
    <%end%>
    <div class = "navbar-burger burger" data-target="navbarExample">
    <span></span>
    <span></span>
    <span></span>

    </div>
  </div>

  <div id="navbarExample" class = "navbar-menu">
    <div class = "navbar-end">
      <div class ="field is-grouped">
        <p class = "control">
          <%= link_to "New Clink", new_clink_path, class: "button is-info is-inverted" %>
        </p>
     <% if user_signed_in? %>
              <p class="control">
                <%= link_to current_user.name, edit_user_registration_path, class: "button is-info" %>
              </p>
              <p>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"button is-info" %>
              </p>
            <% else %>
            <p class="control">
              <%= link_to 'Sign In', new_user_session_path, class: "button is-info" %>
            </p>
						<p class="control">
              <%= link_to 'Sign Up', new_user_registration_path, class: "button is-info" %>
            </p>
            <% end %>
  </div>
    </div>
      </div>
  </nav>





    <%= yield %>
  </body>
</html>